import Head from "next/head";
import TopBar from "@/components/Topbar"
import UploadFiles from "@/components/UploadFiles";

export default function Home() {
  return (
    <>
      <Head>
        <title>Google Drive Clone</title>
        <meta name="description" content="A Google Drive clone generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <TopBar />
        <UploadFiles />
      </main>
    </>
  );
}
