import Head from "next/head";
import Button from "@/components/Button"
import { useSession, signIn, signOut } from "next-auth/react"


export default function Home() {
  const { data: session } = useSession()
  console.log(session)
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          {session ? 
            <div className="flex flex-col items-center">
              <h2 className="text-4xl text-white">Welcome {session.user.name}</h2>
              <Button onClick={() => signOut()} btnClass="btn-secondary" btnText="Sign out"></Button>
            </div>
            : <Button onClick={() => signIn()} btnClass="btn-secondary" btnText="Sign in"></Button>
          }
        </div>
      </main>
    </>
  );
}
