import Head from "next/head";
import TopBar from "@/components/Topbar"
import UploadFiles from "@/components/UploadFiles";
import ShowFiles from "@/components/ShowFiles";

export default function Home() {
  return (
    <>
      <Head>
        <title>Google Drive Clone</title>
        <meta name="description" content="A Google Drive clone generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen" data-theme="dim">
        <TopBar />
        <UploadFiles />
        <ShowFiles />
      </main>
    </>
  );
}
