import Head from "next/head";
import TopBar from "@/components/Topbar"
import UploadFiles from "@/components/UploadFiles";
import { useFetchSession } from "@/hooks/useSession"

export default function Layout({ children }) {
    const { session } = useFetchSession()
    return (
        <>
        <Head>
            <title>Google Drive Clone</title>
            <meta name="description" content="A Google Drive clone generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="min-h-screen" data-theme="dim">
            <TopBar />
            { 
                session ? 
                <>
                    <UploadFiles />
                    { children }
                </>
                : null
            }
        </main>
        </>

    )
}
